/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fabriqueurTicketsPackage
import tornadofx.*
class MyApp : App(CreatorView::class){
}

fun main(args: Array<String>) {
    launch<MyApp>(args)
}
