/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fabriqueurTicketsPackage

import fabriqueurTicketsPackage.views.CreatorView
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.transactions.transaction
import tornadofx.*

class MyApp : App(CreatorView::class){
}

fun main(args: Array<String>) {
    launch<MyApp>(args)
    Database.connect("jdbc:h2:mem:regular", driver = "org.h2.Driver")
}
